version: '3'
services:
  redis5.0:
    image: 'redis:5.0'
    container_name: redis_5.0
    command: redis-server --requirepass 123456
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - "./data:/data"
