FROM anapsix/alpine-java:8_jdk_unlimited

MAINTAINER 2fx0one@gmail.com 

ENV TZ=Asia/Shanghai
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime; echo 'Asia/Shanghai' > /etc/timezone

#RUN set -eux; \
    #ln -snf /usr/share/zoneinfo/$TZ /etc/localtime; \
    #echo $TZ > /etc/timezone
#RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone



