version: '3.6'
services:
  jira:
    build: ./jira
    container_name: jira
    restart: always
    ports:
        - '8080:8080'
    volumes:
      - ./data/jira/var/:/var/atlassian/jira/
      - ./data/jira/logs/:/opt/atlassian/jira/logs/
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
  
  confluence:
    build: ./confluence
    container_name: confluence
    restart: always
    ports:
        - '8090:8090'
    volumes:
      - ./data/confluence/var/:/var/atlassian/confluence/
      - ./data/confluence/logs/:/opt/atlassian/confluence/logs/
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
  
  postgresql:
    image: postgres:9.5-alpine
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira'
      # CHANGE THE PASSWORD!
      - 'POSTGRES_PASSWORD=jellyfish'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"