version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean:1.18.1
    container_name: jenkins_blueocean
    restart: always
    ports:
      - '50000:50000'
      - '50001:8080'
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Duser.timezone=Asia/Shanghai"
