version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins_blueocean
    restart: always
    ports:
      - '50005:50000'
      - '50006:8080'
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Duser.timezone=Asia/Shanghai"
# tips NEED THIS CMD: chown -R 1000:1000 ..
# tips apk add nodejs && apk add npm

# cat ~/.npmrc 加快速度
#home=https://npm.taobao.org
#registry=https://registry.npm.taobao.org/
#sass_binary_site=https://npm.taobao.org/mirrors/node-sass/
