version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins_blueocean
    restart: always
    ports:
      - '50005:50000'
      - '50006:8080'
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Duser.timezone=Asia/Shanghai"
# NEED THIS CMD: chown -R 1000:1000 ..