version: '3'
services:
  java8:
    image: 'ccr.ccs.tencentyun.com/wmd_repos/wmd-shop-java:0.0.7'
    container_name: shop
    restart: always
    ports:
      - '8894:8894'
    volumes:
      - ./log:/app/log
      - ./config:/app/config
