version: '2'
services:
    gitlab:
      container_name: gitlab
      image: 'twang2218/gitlab-ce-zh:11.1.4'
      restart: always
      environment:
        TZ: 'Asia/Shanghai'
      ports:
        - '50080:50080'
      volumes:
        - ./config:/etc/gitlab
        - ./data:/var/opt/gitlab
        - ./logs:/var/log/gitlab
