version: '3'
services:
  jenkins:
    image: 'jenkinsci/blueocean'
    container_name: jenkins
    restart: always
    ports:
      - '50000:50000'
      - '8080:8080'
    volumes:
      - .:/var/jenkins_home
