version: '3.6'
services:
  jira:
    build: .
    container_name: jira
    restart: always
    ports:
        - '8080:8080'
    volumes:
      - ./data/jira/var/:/var/atlassian/jira/
      - ./data/jira/logs/:/opt/atlassian/jira/logs/
  
  postgresql:
    image: postgres:9.5-alpine
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira'
      - 'POSTGRES_PASSWORD=jellyxxxxfish'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'