version: '3'
services:
  mysql8:
    restart: always
    image: mysql:8
    container_name: mysql8
    ports:
      - "3305:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --default-time-zone=+8:00
      --innodb_buffer_pool_size=128M
      --max_allowed_packet=256M
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      TZ: Asia/Shanghai
    volumes:
      - "./db:/var/lib/mysql"
      - "./conf/my.cnf:/etc/my.cnf"
      - "./init:/docker-entrypoint-initdb.d/"