version: '3'
services:
  influxdb:
    image: 'influxdb:1.7'
    container_name: influxdb
    restart: always
    ports:
      - '8086:8086'
    volumes:
      - "./influxdb:/var/lib/influxdb"
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_DB: cadvisor
      INFLUXDB_USER: cadvisor
      INFLUXDB_USER_PASSWORD: cadvisor
