version: '3'
services:
  mysql:
    image: 'mysql:5.7'
    container_name: mysql_5.7
    restart: always
    ports:
      - '0.0.0.0:3306:3306'
    volumes:
      - "./db:/var/lib/mysql"
      - "./conf/my.cnf:/etc/my.cnf"
      - "./init:/docker-entrypoint-initdb.d/"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      TZ: Asia/Shanghai