version: '3'
services:
  gogs:
    container_name: gogs
    image: gogs/gogs:0.11.91
    links:
      - mysql-gogs:mysql
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - ./gogs:/data/gogs
    restart: always

  mysql-gogs:
    container_name: mysql_gogs
    image: mysql:5.7.27
    # ports:
      # - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
      - "./db-conf/my.cnf:/etc/my.cnf"
    environment:
      - MYSQL_DATABASE=gogs
      - MYSQL_USER=gogs
      - MYSQL_PASSWORD=gogs
      - MYSQL_ROOT_PASSWORD=123456
    command: mysqld --lower_case_table_names=1 --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
