version: '3'
services:
  gogs:
    container_name: gogs
    image: gogs/gogs:0.12.3
    links:
      - postgres-gogs:postgres
    ports:
      - "50002:22"
      - "50003:3000"
    volumes:
      - ./gogs:/data
    restart: always
    depends_on: 
      - postgres-gogs

  postgres-gogs:
    container_name: gogs_postgres
    image: postgres:9.6.15-alpine
    # ports:
      # - "3306:3306"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=gogs
    restart: always
