version: '3'
services:
  gogs:
    container_name: gogs
    image: gogs/gogs:0.12.3
    links:
      - postgres-gogs:postgres
    ports:
      - "50022:22"
      - "53000:3000"
    volumes:
      - ./data-gogs-repositories:/data/git/gogs-repositories
      - ./data-gogs:/data/gogs
    restart: always
    depends_on: 
      - postgres-gogs

  postgres-gogs:
    container_name: gogs_postgres
    image: postgres:9.6.15-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gogs
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=gogs
    restart: always

# head.tmpl 放在 data-gogs/templates/base