version: '3'
services:
  gogs:
    container_name: gogs
    image: gogs/gogs:0.11.91
    links:
      - postgres-gogs:postgres
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - ./gogs:/data/gogs
    restart: always
    depends_on: 
      - postgres-gogs

  postgres-gogs:
    container_name: postgres_gogs
    image: postgres:9.6.15-alpine
    # ports:
      # - "3306:3306"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gogs
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=gogs
    restart: always
